# Generated by Django 5.1.6 on 2025-02-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userregister",
            name="username",
        ),
    ]
