# Generated by Django 5.1.6 on 2025-02-10 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerTickets",
            fields=[
                ("Ticket_Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Issue_Type",
                    models.CharField(
                        choices=[
                            ("Billing", "Billing"),
                            ("Order", "Order"),
                            ("Technical", "Technical"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("Description", models.TextField()),
                (
                    "Ticket_Status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                ("Updated_At", models.DateTimeField(auto_now_add=True)),
                (
                    "User_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
