# Generated by Django 5.1.6 on 2025-02-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("Payment_Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Payment_Mode",
                    models.CharField(
                        choices=[
                            ("Card/Credit", "Credit Card"),
                            ("Card/Debit", "Card Debit"),
                            ("COD", "COD"),
                            ("UPI", "UPI"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Payment_Status",
                    models.CharField(
                        choices=[
                            ("Successful", "Successful"),
                            ("Pending", "Pending"),
                            ("Failed", "Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("Payment_Date", models.DateTimeField(auto_now_add=True)),
                (
                    "Order_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
    ]
