# Generated by Django 5.1.6 on 2025-02-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("Inventory_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Stock_Quantity", models.IntegerField()),
                ("Restock_Date", models.DateTimeField(auto_now_add=True)),
                (
                    "Product_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
        ),
    ]
