# Generated by Django 5.1.6 on 2025-02-11 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("Category_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Category_Name", models.CharField(max_length=255)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("Product_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Product_Name", models.CharField(max_length=255)),
                ("Product_Description", models.TextField()),
                ("Product_Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Product_Stock_Quantity", models.IntegerField()),
                (
                    "Product_Image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                ("Is_Active", models.BooleanField(default=False)),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategory",
                    ),
                ),
                (
                    "Seller",
                    models.ForeignKey(
                        limit_choices_to={"role": "SELLER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                ("wishlist_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to="products.products",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist Item",
                "verbose_name_plural": "Wishlist Items",
                "unique_together": {("user", "product")},
            },
        ),
    ]
