# Generated by Django 5.1.6 on 2025-02-10 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("Cart_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                ("Is_Active", models.BooleanField(default=True)),
                (
                    "User_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("CartItem_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Cart_Quantity", models.PositiveIntegerField()),
                ("Cart_Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Added_At", models.DateTimeField(auto_now=True)),
                (
                    "Cart_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Cart.cart"
                    ),
                ),
                (
                    "Product_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
        ),
    ]
