# Generated by Django 5.1.6 on 2025-02-10 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feedback_text", models.TextField()),
                (
                    "sentiment_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        choices=[
                            ("Positive", "Positive"),
                            ("Neutral", "Neutral"),
                            ("Negative", "Negative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("executive_action", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"role": "User"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sentiment Analysis",
                "verbose_name_plural": "Sentiment Analyses",
            },
        ),
    ]
