# Generated by Django 5.1.6 on 2025-02-10 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnedRequestProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Return_Reason", models.TextField()),
                ("Return_Status", models.CharField(max_length=20)),
                ("Requested_At", models.DateTimeField(auto_now_add=True)),
                ("Updated_At", models.DateTimeField(auto_now=True)),
                (
                    "Order_Item_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orderitem",
                    ),
                ),
                (
                    "Product_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
                (
                    "Return_Request_Id",
                    models.ForeignKey(
                        limit_choices_to={"role": "User"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnProducts",
            fields=[
                (
                    "Return_Entry_Id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Return_Status", models.CharField(max_length=30)),
                ("Seller_Confirmation", models.BooleanField()),
                ("Return_Quantity", models.IntegerField()),
                ("Return_Remark", models.TextField()),
                ("Confirmed_At", models.DateTimeField(auto_now_add=True)),
                (
                    "Product_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
                (
                    "Return_Request_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="returnscustomer.returnedrequestproduct",
                    ),
                ),
            ],
        ),
    ]
