# Generated by Django 5.1.6 on 2025-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returnscustomer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnedrequestproduct",
            name="Return_Status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="returnproducts",
            name="Return_Status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_transit", "In Transit"),
                    ("received", "Received"),
                    ("damaged", "Damaged"),
                ],
                max_length=30,
            ),
        ),
    ]
