# Generated by Django 5.1.6 on 2025-02-12 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returnscustomer", "0002_alter_returnedrequestproduct_return_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returnedrequestproduct",
            name="id",
        ),
        migrations.AddField(
            model_name="returnedrequestproduct",
            name="customer_id",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"role": "User"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="returnedrequestproduct",
            name="Return_Request_Id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
